#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_mulle-scion-import-private.h
src/reflect/_mulle-scion-include-private.h
)

set( PRIVATE_HEADERS
src/import-private.h
src/include-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_mulle-scion-import.h
src/reflect/_mulle-scion-include.h
)

set( PUBLIC_HEADERS
src/MulleHoedown+MulleScionPrinting.h
src/MulleScionObjectModel+WebServer.h
src/NSString+TrimTextFromExamples.h
src/WebServer.h
src/import.h
src/include.h
src/version.h
)

