# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/resources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-resource--resources
#
set( RESOURCES
dox/MulleScionDataFlow.graffle/data.plist
dox/MulleScionDataFlow.graffle/image1.tiff
dox/MulleScionDataFlow.graffle/image2.tiff
dox/MulleScionDataFlow.png
dox/MulleScionTemplatesDataFlow.graffle/data.plist
dox/MulleScionTemplatesDataFlow.graffle/image1.tiff
dox/MulleScionTemplatesDataFlow.graffle/image2.tiff
dox/MulleScionTemplatesDataFlow.png
)
