#
# This file will be included by cmake/share/resources.cmake
#
# cmake/reflect/_Resources.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-resource--resources
#
set( RESOURCES
dox/MulleScionDataFlow.graffle/data.plist
dox/MulleScionDataFlow.graffle/image1.tiff
dox/MulleScionDataFlow.graffle/image2.tiff
dox/MulleScionDataFlow.png
dox/MulleScionTemplatesDataFlow.graffle/data.plist
dox/MulleScionTemplatesDataFlow.graffle/image1.tiff
dox/MulleScionTemplatesDataFlow.graffle/image2.tiff
dox/MulleScionTemplatesDataFlow.png
)
