#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleHoedown+MulleScionPrinting.m
src/MulleScionObjectModel+WebServer.m
src/NSString+TrimTextFromExamples.m
src/WebServer.m
src/main.m
)
