# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--resources
#
set( RESOURCES
dox/Environment_Variables.scion
dox/Expressions.scion
dox/Formatting_Options.scion
dox/Global_Variables.scion
dox/!_Introduction.scion
dox/NSMakeRange.scion
dox/block.scion
dox/concat.scion
dox/define.scion
dox/__demo.scion
dox/dot.scion
dox/exists.scion
dox/extends.scion
dox/filter.scion
dox/for.scion
dox/if.scion
dox/includes.scion
dox/index.scion
dox/log.scion
dox/macro.scion
dox/__page.scion
dox/properties.plist
dox/requires.scion
dox/#!.scion
dox/[].scion
dox/|.scion
dox/__scion_banner.scion
dox/__scion_footer.scion
dox/__scion_macros.scion
dox/__scion_navigation.scion
dox/__scion_page.scion
dox/__scion_style.scion
dox/self.scion
dox/set.scion
dox/_spaces.scion
dox/verbatim.scion
dox/while.scion
dox/_wrapper.scion
)

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/MulleMarkdown+MulleScionPrinting.m
src/MulleMarkdown.m
src/MulleScionObjectModel+WebServer.m
src/NSString+TrimTextFromExamples.m
src/WebServer.m
src/main.m
)
