#ifndef mulle_scion_import_h__
#define mulle_scion_import_h__

/* This is a central include file to keep dependencies out of the library
   Objective-C files. It is usally imported by Objective-C .h files only.
   .m and .aam use import-private.h.
*/

/*
   Get C includes first
 */
#include "include.h"

/* Include the header file automatically generated by c-sourcetree-update.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */
#import "_mulle-scion-import.h"
#ifndef MULLE_SCION_EXTERN_GLOBAL
# define MULLE_SCION_EXTERN_GLOBAL MULLE_C_EXTERN_GLOBAL
#endif


#endif
