/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_scion_import_h__
#define _mulle_scion_import_h__

// How to tweak the following Foundation #import
//    remove:          `mulle-sourcetree mark Foundation no-header`
//    rename:          `mulle-sourcetree mark Foundation set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark Foundation [no-]import`
//    toggle public:   `mulle-sourcetree mark Foundation [no-]public`
//    toggle optional: `mulle-sourcetree mark Foundation [no-]require`
//    remove for os:   `mulle-sourcetree mark Foundation no-os-<osname>`
# import <Foundation/Foundation.h>   // Foundation

// How to tweak the following MulleScion #import
//    remove:          `mulle-sourcetree mark MulleScion no-header`
//    rename:          `mulle-sourcetree mark MulleScion set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark MulleScion [no-]import`
//    toggle public:   `mulle-sourcetree mark MulleScion [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleScion [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleScion no-os-<osname>`
# import <MulleScion/MulleScion.h>   // MulleScion

// How to tweak the following MulleHoedown #import
//    remove:          `mulle-sourcetree mark MulleHoedown no-header`
//    rename:          `mulle-sourcetree mark MulleHoedown set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark MulleHoedown [no-]import`
//    toggle public:   `mulle-sourcetree mark MulleHoedown [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleHoedown [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleHoedown no-os-<osname>`
# import <MulleHoedown/MulleHoedown.h>   // MulleHoedown

// How to tweak the following MulleWebServer #import
//    remove:          `mulle-sourcetree mark MulleWebServer no-header`
//    rename:          `mulle-sourcetree mark MulleWebServer set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark MulleWebServer [no-]import`
//    toggle public:   `mulle-sourcetree mark MulleWebServer [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleWebServer [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleWebServer no-os-<osname>`
# import <MulleWebServer/MulleWebServer.h>   // MulleWebServer

#include "_mulle-scion-include.h"


#endif
