/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_scion_import_h__
#define _mulle_scion_import_h__

// How to tweak the following Foundation #import
//    remove:             `mulle-sourcetree mark Foundation no-header`
//    rename:             `mulle-sde dependency|library set Foundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark Foundation [no-]import`
//    toggle localheader: `mulle-sourcetree mark Foundation [no-]localheader`
//    toggle public:      `mulle-sourcetree mark Foundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark Foundation [no-]require`
//    remove for os:      `mulle-sourcetree mark Foundation no-os-<osname>`
# if defined( __has_include) && __has_include("Foundation.h")
#   import "Foundation.h"   // Foundation
# else
#   import <Foundation/Foundation.h>   // Foundation
# endif

// How to tweak the following MulleScion #import
//    remove:             `mulle-sourcetree mark MulleScion no-header`
//    rename:             `mulle-sde dependency|library set MulleScion include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleScion [no-]import`
//    toggle localheader: `mulle-sourcetree mark MulleScion [no-]localheader`
//    toggle public:      `mulle-sourcetree mark MulleScion [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleScion [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleScion no-os-<osname>`
# if defined( __has_include) && __has_include("MulleScion.h")
#   import "MulleScion.h"   // MulleScion
# else
#   import <MulleScion/MulleScion.h>   // MulleScion
# endif

// How to tweak the following MulleHoedown #import
//    remove:             `mulle-sourcetree mark MulleHoedown no-header`
//    rename:             `mulle-sde dependency|library set MulleHoedown include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleHoedown [no-]import`
//    toggle localheader: `mulle-sourcetree mark MulleHoedown [no-]localheader`
//    toggle public:      `mulle-sourcetree mark MulleHoedown [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleHoedown [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleHoedown no-os-<osname>`
# if defined( __has_include) && __has_include("MulleHoedown.h")
#   import "MulleHoedown.h"   // MulleHoedown
# else
#   import <MulleHoedown/MulleHoedown.h>   // MulleHoedown
# endif

// How to tweak the following MulleWebServer #import
//    remove:             `mulle-sourcetree mark MulleWebServer no-header`
//    rename:             `mulle-sde dependency|library set MulleWebServer include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleWebServer [no-]import`
//    toggle localheader: `mulle-sourcetree mark MulleWebServer [no-]localheader`
//    toggle public:      `mulle-sourcetree mark MulleWebServer [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleWebServer [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleWebServer no-os-<osname>`
# if defined( __has_include) && __has_include("MulleWebServer.h")
#   import "MulleWebServer.h"   // MulleWebServer
# else
#   import <MulleWebServer/MulleWebServer.h>   // MulleWebServer
# endif

#ifdef __has_include
# if __has_include( "_mulle-scion-include.h")
#  include "_mulle-scion-include.h"
# endif
#endif


#endif
