/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 5C7B0A16-98BA-4D02-90ED-FAD925D8C216 instead of Foundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark Foundation no-header`
//    rename:             `mulle-sde dependency|library set Foundation include whatever.h`
//    reorder:            `mulle-sourcetree move Foundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark Foundation [no-]import`
//    toggle public:      `mulle-sourcetree mark Foundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark Foundation [no-]require`
//    remove for platform:`mulle-sourcetree mark Foundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <Foundation/Foundation.h>   // Foundation

// You can tweak the following #import with these commands.
// (Use CE994F9D-CBD0-4CA9-BC81-96B12D0BBB69 instead of MulleScion if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleScion no-header`
//    rename:             `mulle-sde dependency|library set MulleScion include whatever.h`
//    reorder:            `mulle-sourcetree move MulleScion <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleScion [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleScion [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleScion [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleScion no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleScion/MulleScion.h>   // MulleScion

// You can tweak the following #import with these commands.
// (Use 671DBE4D-4DB4-4AE9-AA29-C96136355B21 instead of MulleHoedown if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleHoedown no-header`
//    rename:             `mulle-sde dependency|library set MulleHoedown include whatever.h`
//    reorder:            `mulle-sourcetree move MulleHoedown <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleHoedown [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleHoedown [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleHoedown [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleHoedown no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleHoedown/MulleHoedown.h>   // MulleHoedown

// You can tweak the following #import with these commands.
// (Use D7FD831D-5E53-4BFD-B938-BC6C546A4D62 instead of MulleWebServer if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleWebServer no-header`
//    rename:             `mulle-sde dependency|library set MulleWebServer include whatever.h`
//    reorder:            `mulle-sourcetree move MulleWebServer <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleWebServer [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleWebServer [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleWebServer [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleWebServer no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleWebServer/MulleWebServer.h>   // MulleWebServer

#ifdef __has_include
# if __has_include( "_mulle-scion-include.h")
#  include "_mulle-scion-include.h"
# endif
#endif

