/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_PRIVATEIMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_scion_import_private_h__
#define _mulle_scion_import_private_h__

/* no headers */

#ifdef __has_include
# if __has_include( "_mulle-scion-include.h")
#  include "_mulle-scion-include-private.h"
# endif
#endif

#endif
